services:
  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    healthcheck:
      test: echo "version" | nc -vn -w 1 127.0.0.1 11211
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j:/data
    environment:
      NEO4J_AUTH: none
      NEO4J_server_memory_pagecache_size: 2G
      NEO4J_server_memory_heap_initial__size: 2G
      NEO4J_server_memory_heap_max__size: 4G
      NEO4J_PLUGINS: '["apoc"]'
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
  sink:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: sink
    ports:
      - "8081:8081"
    depends_on:
      neo4j:
        condition: service_healthy
      memcached:
        condition: service_healthy
    environment:
      neo4j_uri: neo4j://neo4j:7687
      neo4j_user: neo4j
      neo4j_pass: neo4j
      SUBSTREAMS_API_TOKEN: ${SUBSTREAMS_API_TOKEN}
      SUBSTREAMS_ENDPOINT_URL: ${SUBSTREAMS_ENDPOINT_URL}
      SUBSTREAMS_START_BLOCK: ${SUBSTREAMS_START_BLOCK}
      memcached_uri: memcached:11211
      memcached_default_expiry: "3600"
  # api:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile
  #     target: api
  #   ports:
  #     - "80:8080"
  #   depends_on:
  #     neo4j:
  #       condition: service_healthy
  #     memcached:
  #       condition: service_healthy
  #   environment:
  #     neo4j_uri: neo4j://neo4j:7687
  #     neo4j_user: neo4j
  #     neo4j_pass: neo4j
  #     memcached_uri: memcached:11211
  #     memcached_default_expiry: "3600"

  mcp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: mcp
    ports:
      - "80:8080"
    depends_on:
      neo4j:
        condition: service_healthy
      memcached:
        condition: service_healthy
    environment:
      neo4j_uri: neo4j://neo4j:7687
      neo4j_user: neo4j
      neo4j_pass: neo4j
      memcached_uri: memcached:11211
      memcached_default_expiry: "3600"
